=== GerardoPerezArenas/palomitas/src/main/webapp/sigpLicense.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.altia.es/sigp/sigpLicense"
            xmlns="http://www.altia.es/sigp/sigpLicense"
            elementFormDefault="qualified">
        
<xsd:complexType name="License">
    <xsd:sequence>
         <xsd:element name="description" type="xsd:string"/>
         <xsd:element name="signature" type="xsd:string"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="ModuleLicense" block="extension">
    <xsd:complexContent>
        <xsd:extension base="License">
            <xsd:sequence>
                <xsd:element name="module-id" type="xsd:short"/>
                <xsd:element name="expiration-date" type="xsd:string"/>
            </xsd:sequence>
        </xsd:extension>         
    </xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="ParamLicense" block="extension">
    <xsd:complexContent>
        <xsd:extension base="License">
            <xsd:sequence>
                <xsd:element name="param-id" type="xsd:string"/>                
            </xsd:sequence>
        </xsd:extension>         
    </xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="MaxUsersLicense" block="extension">
    <xsd:complexContent>
        <xsd:extension base="ParamLicense">
            <xsd:sequence>
                <xsd:element name="max-users" type="xsd:int"/>                
            </xsd:sequence>
        </xsd:extension>         
    </xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="Sigp-Licenses">
    <xsd:sequence>
		<xsd:element name="sigp-license" type="License" minOccurs="1" maxOccurs="unbounded"/>				        		
    </xsd:sequence>
</xsd:complexType>

<xsd:element name="sigp-licenses" type="Sigp-Licenses"/>

</xsd:schema>

=== GerardoPerezArenas/palomitas/src/main/webapp/licenses.xml
<?xml version="1.0" encoding="UTF-8"?>
<sigp-licenses xsi:schemaLocation="http://www.altia.es/sigp/sigpLicense sigpLicense.xsd" xmlns="http://www.altia.es/sigp/sigpLicense" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<sigp-license xsi:type="ModuleLicense">
<description>Entrada-salida</description>
<signature>P90EXIcBbYTMsMFwVyhUisrLQ5eNs2WmRNEv/cAbeNbRfgvIIa6bcSf6kNoLIlHuiEYyH2zEFy5w
Nqh2hkuQoIw6cEn32QlH19a1QRWlOD7FX9GAWCgd11E8LfbHDTa1+wUt5DaqX/3pzt/WCM7ERMZY
XpxrDSfLC4YOGatbcUVT50DpSf+kgxV3ROwZq6TQ9GVEZuwa24FbjA9prmz+8y0BjU1jA7A3y8O9
3JfjriJZK4sYJGjBLccMhFwjgojjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</signature>
<module-id>1</module-id>
<expiration-date>NUNCA</expiration-date>
</sigp-license>
<sigp-license xsi:type="ModuleLicense">
<description>Terceros</description>
<signature>NgBE8QkcJtjP9UG6Bnt6YIm7S+BmxeoQ/DYVPib8K/ADF3HgYZli7mELIec4KmNJwKb/SpfCM5N8
aR4dWGFptoDz0XoB40ryoCke7dEsKHe6aUH8sPE04RsDxeZDwKAYFSNiWVBPpQtBC//ESqvIoNc/
eeVoe4XfP8XbjTRkQKxxp/LPbiDGuJdccoMBjQvgGkOIWZMQNFGFON/pqBeRPmTkofyixoPoq1SA
jkVCWtkANRh38sciROU4U3M6DqGXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</signature>
<module-id>3</module-id>
<expiration-date>NUNCA</expiration-date>
</sigp-license>
<sigp-license xsi:type="ModuleLicense">
<description>Expedientes</description>
<signature>P90EXIcBbYTMsMFwVyhUisrLQ5eNs2WmRNEv/cAbeNbRfgvIIa6bcSf6kNoLIlHuiEYyH2zEFy5w
Nqh2hkuQoGlSs0V4zweomiWFUiLpGyoMZCXVcKN9CC29jHS/cl7ZU3Cbvsf2udvfPE4YcPDCUpii
kxzHm+7W9g3SMduuvIB70pOGtu4TgTSBJo+DAW6X9rV+82tL3l9rsBjjP4E7kZKNxlTEZ7XN1GMx
YEzLjH76aQ/0sreYgPIlQPomgUGKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</signature>
<module-id>4</module-id>
<expiration-date>NUNCA</expiration-date>
</sigp-license>
<sigp-license xsi:type="ModuleLicense">
<description>Administrador general</description>
<signature>Roh2YjF6ll4koom+jdGEk5o+coVf6is4CBIPEELwM/ry3mKzWHGsRcvkpyvdoj+v+NgwPT2nmNA3
rMbcAKbDv1Yi5D1pJgjuwrZUb2OGvtBhbKKW9Gm6LpyzGuOjzfdk/5+isDz2bBDfO5ZmhJvloBko
Y5kB6Y8MLTSU3ZLGBKZhLJkWSpFLCxoq0X1TwrxRYTstDMMLSy0wMK2X7uoVa5mfWTRlOcglK66O
GrjWUza1uv8eG9cjfjbI4EhQcQQ0nEFLlC6oxzj4hdHH67OWdSQ/ZYx9nwRLIX18orda/cGxt2g2
h2Jov4R89ElncUvBmq4jUViqqti5tHNXhMEDZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</signature>
<module-id>5</module-id>
<expiration-date>NUNCA</expiration-date>
</sigp-license>
<sigp-license xsi:type="ModuleLicense">
<description>Documentos</description>
<signature>ACTj7CyHxfzcDaeZp2ICFsmdvBw7+87FBmRsEHtSE6S6Ud4fxwu+pHmmKAT1I1DCYuSUUX5spRHY
DykaRC4LuEXsQX2nO2ZnKJz3kkBDpQeLGNINH7/X6xnE00zCMWfvszK5LlZXdisgegFrs8RDWvQe
0HDM3+v9zNKD8ArB90AKjYVqhgAbiloiTVvqUK9PKbHgsj3YVaxzDyprAQUzenO47eahsOCl+KuP
6Mxe02H+yId0XOPuDn/+8ugBuy1tAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</signature>
<module-id>6</module-id>
<expiration-date>NUNCA</expiration-date>
</sigp-license>
<sigp-license xsi:type="ModuleLicense">
<description>Administrador local</description>
<signature>Roh2YjF6ll4koom+jdGEk5o+coVf6is4CBIPEELwM/ry3mKzWHGsRcvkpyvdoj+v+NgwPT2nmNA3
rMbcAKbDv5vFchApw/nXLSVzAxR7xhjmqclz9PMEYb1rG98lN5nnYnehHk6gfnAW6tjlDUsLotam
/bUM9oJ48tpBBpvWlY6TLolSX2mnTKgkBGR+Pz1tahsEjPnGmR0Gb4FXyuZtTiHdvVAYwzsKZOVQ
/zNXvofxyAVx2zn0DJX4LmyVFM86JiCKxCQD/XpANZo64sARaErV6Dt+D7kU3zwR5MRKYosNH0cf
mtghRG/6HVdHoeco4UNRVG605+7JO0ecGmwaBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</signature>
<module-id>9</module-id>
<expiration-date>NUNCA</expiration-date>
</sigp-license>
<sigp-license xsi:type="ModuleLicense">
<description>Informes de direccion</description>
<signature>enWpC4SJhLzjXkxK4iFHdyFkMJzu4HukLQt9bl6FzymqNgtzBaASJM0fSnXF86YFzMCwr7obvwvw
4tyNkdV/eTZmWoU4nVSeUl8/393l9D4ZWKYV4vaY66BmWqmHCId855bVVtuQk6tatzcWpH9Ef78O
7nvD0fkVOXSUm5gCb8NaEf2SDkHa7ypadOjyym3hi85KaS+QMWye4TdRihnDXSesfzH033w1DZA+
1hNwo3rl4CpT6P9FFAY/zYu6mqi0U3xUwmhG2mxm9kBDIRbePrtojO/sjhOsBxAmfpFSCEn17xq8
TAqIvzLaJXde8RLDd6hzlkHHG1Sj+1T+Kkj7wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</signature>
<module-id>10</module-id>
<expiration-date>NUNCA</expiration-date>
</sigp-license>
<sigp-license xsi:type="ModuleLicense">
<description>Portafirmas</description>
<signature>ed1zBV927F1azCdZtFyQFiJQH6E5/m99TZTP6SP5IK97zshrOH6HNm+zgAnjk1cIZmUFs6K8R+T2
vLt5ODwV3kvIsP10HXnsc62K3M2SuWT0aOUJp5fbbvBiKpmCTydEgFBv/EnWVw4PbffGx2AcLjoD
WU6j3vfnLv/8VQVNMkML59UG+bqkwljE7JPMyGgWFRSM1f7h7GJPYccFMvJ04ODK3OuMYlzhSxxA
0MkkSZiMaabcp4Xjh+pEWoZ8e3wYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</signature>
<module-id>11</module-id>
<expiration-date>NUNCA</expiration-date>
</sigp-license>
<sigp-license xsi:type="ModuleLicense">
<description>Gestion formularios</description>
<signature>mKlvb8qAhzi5EXF0LSec0Hl34yAJNOFsCUaC2aO2aFHOGKMHdCajgawZKcCR8r49tKkdJ3qFS4ok
RfURzxbv4kz6LoA6YfuO5/nbpbsHRxjtKUQGQPqjSvEAFc5uk1ZTFarIIJyA2yviSCsdSrpxkRb/
D+L1k+YO6zh0Irvk0qVLcy18qgXHdvXBKPcfjehhXBrtuBtaCYGDTxmLZ3PDYnJeHIXsw6VY+wqk
amGpEkcnqGgRjRr0lAwOdU61/kGmEtcvA5O3VDozAo5gbEwuRNfZVZgjVFtjDOGRaY5fg1SkYWqf
8zEpNuAUv/PG+XFdtdI/VAY8+nfJ5dVsKBK0wgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</signature>
<module-id>15</module-id>
<expiration-date>NUNCA</expiration-date>
</sigp-license>
<sigp-license xsi:type="ModuleLicense">
<description>Gestion informes</description>
<signature>mKlvb8qAhzi5EXF0LSec0Hl34yAJNOFsCUaC2aO2aFHOGKMHdCajgawZKcCR8r49tKkdJ3qFS4ok
RfURzxbv4pqJvLfXFwFu3gxY7qAWQRuYfw4u9Ur3RqGK0hptbf/mqrRHMz27OQEDNv5ZQDXCfpNb
FGj0qRHiCekWgE7cLbkxTUW77PxtIH8g8pJ5QkPf8gFbmBlndKPBVxCRkqeUxlf2RRYN+gSxgWNN
r9dsvdtSajsZl2LAs5NWiztOUzrfjb1vtH5scGBxWK/5Ih4F3pti+B+SnlQenaTozTEGgHT79vWp
uxe/lAD0lTp0vSM8z4tJm6OrkVEtTdSjMdyn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</signature>
<module-id>16</module-id>
<expiration-date>NUNCA</expiration-date>
</sigp-license>
<sigp-license xsi:type="ModuleLicense">
<description>Servicios web</description>
<signature>gHEimAfaHPViDuh0EHd0xiIDssN4Fw5MLs4ssS3pRCge/R3g94yvW1GJelLjNlRCcfT0pRuOwMao
P2WOhiCRQweHZvxyZue9zG8Us3NEeB+Q51jpsw5aKUGf0KrdvCctHtdDJUHtQE4JTycnAW4OP789
8DsxdYiL8KQaU6kZP3NT50DpSf+kgxV3ROwZq6TQ9GVEZuwa24FbjA9prmz+8y0BjU1jA7A3y8O9
3JfjriJZK4sYJGjBLccMhFwjgojjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</signature>
<module-id>17</module-id>
<expiration-date>NUNCA</expiration-date>
</sigp-license>
<sigp-license xsi:type="ModuleLicense">
